### ISSUE TITLE
libc6_2.23-5_amd64.deb outdated

### ISSUE THREAD

**Issue by babim** [Adam-Ant/docker-alpine-glibc#4]
hi!
Thanks your template. Just want tell you link to libc6_2.23-5_amd64.deb outdated.
change to http://ftp.debian.org/debian/pool/main/g/glibc/libc6_2.24-8_amd64.deb
(y)

**Comment by Adam-Ant** [comment]
Thanks, hadn't realised this was out of date. URL has been updated.

b00ebc8

Closing #4

**Comment by Adam-Ant** [comment]
Just realised alpine 3.5 has been released, so I've upgraded the image as patchelf is no longer in the 3.4 repos. Feel free to raise a new issue if this breaks anything.

**Comment by babim** [comment]
(y)
